### ISSUE TITLE
port to mesosphere

### ISSUE THREAD

**Issue by adeze** [tleyden/elastic-thought#5]
just wondering, do you think this would be easy to port to a mesos/sphere cluster since they run coreOS, and there's a lot of plumbing already.

**Comment by tleyden** [comment]
Funny you mention this!  While at Gophercon, I was talking to @josephjacks from Kismatic about this very subject.  He's ex-Mesosphere, and has his head wrapped around Mesos.  

His take was that although Mesos *might* be appropriate for this project, it's overkill and there's no reason why it can't be solved by Kubernetes and some custom "job routing" logic.

My plan is to get as far as I can with the Kubernetes approach, and if I find myself re-inventing the wheel with thousands of line of code that's already present in the Mesos ecosystem, I'll rethink things.

Regardless, Mesos is definitely on the radar.  Feel free to continue making an argument for it!  Thanks for the feedback and contribution.
